//
//  main.c
//  Chpt9PP3
//
//  Created by Randy McMillan on 11/12/13.
//  Copyright (c) 2013 Randy McMillan. All rights reserved.
//

/*
 
 3. Write and test a recursive function that returns the value of the following recursive definition:
 
 f(x) = 0               if x <= 0
 f(x) = f(x-1) + 2      otherwise
 
 What set of numbers is generated by this definition?
 
 */

#include <stdio.h>
#define LINE	80
#define ZERO	0
#define BLANK	' '
double	input;
char	output[LINE];

double y = 0.0;
double firstFunction(double);
double compositeFunction(double);
void promptInput();
double *scanLine(char *dest, int dest_len);

void promptInput()
{
	printf("Please enter a number --> ");
}


int main(int argc, const char * argv[])
{

	promptInput();
    scanf("%lf",&input);
    printf("\ny =  %lf\n",firstFunction(input));
    
    main(argc,argv);
    return 0;
}



double firstFunction(double x){
    
    
    if (x <= 0) {

        x = 0;
    
    } else {
     
        x = compositeFunction(x-1) + 2;
        
        printf("%lf",x);
    }
    
    return x;
}

double compositeFunction(double x){

    return x-1+2;
    
}

